### PR TITLE
Implement UUID adapter

### PR DESCRIPTION
**Pull request by Turbo87**
This PR adds an UUID adapter to the `StandardJsonAdapters` class that converts between the `java.util.UUID` class and JSON strings.

### CODE REVIEW

**Comment by swankjesse** [comment]
We were planning to deliberately _not_ include type adapters for everything in the JDK, and just let applications embed it themselves.  The code to do it is really quite trivial with our adapter methods API:

```
    Moshi moshi = new Moshi.Builder()
        .add(new Object() {
          @ToJson String toJson(UUID uuid) {
            return uuid.toString();
          }
          @FromJson UUID fromJson(String s) {
            return UUID.fromString(s);
          }
        })
        .build();
```

**Comment by swankjesse** [comment]
Agree/disagree @JakeWharton ?

**Comment by Turbo87** [comment]
@swankjesse Thanks for the quick feedback. To be honest I was a bit tired of implementing the same basic adapter over and over again, and I thought that the `UUID` class was probably basic enough to be integrated into moshi directly. Have you considered publishing additional artifacts like e.g. `moshi-adapter-uuid`?

**Comment by JakeWharton** [comment]
I agree with the policy.

I also sympathize as a consumer. While something like UUID seems obvious,
we'll eventually get to types which aren't clear like Date, File, etc. This
puts us in a precarious position since we have no clear definition of what
gets added and what does not.

**Comment by swankjesse** [comment]
We probably want a _examples_ project like OkHttp, which can include this, plus documentation to explain it!

**Pull request closed without merging**
