### PR TITLE
Made Types.mapKeyAndValueTypes public

### PR DESCRIPTION
**Pull request by nedtwigg**
Helps a lot for adding third-party adapters for e.g. ImmutableMap.

### CODE REVIEW

**Comment by JakeWharton** [comment]
I'm not sure exposing this is the right thing to do. It's not sufficiently general (and neither is the existing collection one). What if I want to serialize Guava's `Table` which has three generic params?

**Comment by nedtwigg** [comment]
Fair enough :)

**Comment by JakeWharton** [comment]
File a bug at least so we can track it?

**Comment by nedtwigg** [comment]
Will do once I have a good story on the complete usecase.  I may have other ways to solve my problem - just saw that similar methods in this class were public and figured it might have been an oversight that this one wasn't as well.

**Comment by nedtwigg** [comment]
I have described the issue better in #449.  And, as you correctly noted, the approach I took here was too specific, and there is a better, more general method, which I made public in #448.

**Pull request closed without merging**
