### PR TITLE
Fix unexpected path when a value is absent from an object

### PR DESCRIPTION
**Pull request by SimonMarquis**
Keep track of the current object path to format the JsonDataException message.

See square/moshi#1415

### CODE REVIEW

**Comment by SimonMarquis** [comment]
Oups, the 1st push had a typo: https://github.com/square/moshi/compare/32d694751e555755b88884f3b3f1e4e0d8939041..7043605568338f8c3fbe298a32e4dd02626fb493

**Comment by SimonMarquis** [comment]
I guess this change must also be applied on the AdapterGenerator as well. I'll try to do that.

**Review by swankjesse — COMMENTED** [review]
Great PR. This is ALMOST perfect. But I have one reservation and it’s a big one. 

`JsonReader.getPath()` is a big slow function and this adds that function to the inner loop of every single object parse. The only sufficiently-performant fix here gets the path only if we actually encounter a problem, and not otherwise.

Unfortunately at the time we know we have a problem it’s difficult to recover that path.

But can we do it anyway? I think we probably can! We need to get the path immediately before calling endObject().

**Comment by swankjesse** [comment]
Here’s a work-in-progress that gets your test passing without precomputing the path. It does introduce more work in the common case, but no extra allocations or method calls.
https://github.com/square/moshi/compare/master...jwilson.1130.more_accurate_paths

**Comment by SimonMarquis** [comment]
I completely get that we should not impact the critical path.
Unfortunately I don't think your version working by the look at the unit tests results, or am I missing something here?

**Comment by swankjesse** [comment]
@SimonMarquis 

My goal is to introduce a behavior change here, which means fixing up a bunch of tests. Currently a JsonReader’s path represents the _previous_ name after its value has been read. This behavior is verified by this test, that is failing on my commit:

```
    JsonReader reader = newReader("{\"a\": 5, \"b\": 5, \"c\": 5, \"d\": 5}");
    reader.beginObject();
    assertEquals("$.", reader.getPath());

    assertEquals(0, reader.selectName(abc));
    assertEquals("$.a", reader.getPath());
    assertEquals(5, reader.nextInt());
    assertEquals("$.a", reader.getPath()); // path is still 'a', even though a’s value has been processed
```

With my experiment we’d introduce a behavior change, where the path would drop the name after its value has been read. We’d need to change the tests to match the new behavior. The test above would change like so:

```
    JsonReader reader = newReader("{\"a\": 5, \"b\": 5, \"c\": 5, \"d\": 5}");
    reader.beginObject();
    assertEquals("$.", reader.getPath());

    assertEquals(0, reader.selectName(abc));
    assertEquals("$.a", reader.getPath());
    assertEquals(5, reader.nextInt());
    assertEquals("$.", reader.getPath()); // different!
```

I’m okay with this, especially since it improves the missing field error.

**Comment by SimonMarquis** [comment]
Thank you for clarifying that.
I'll try to update the remaining tests and JsonReaders.

**Comment by SimonMarquis** [comment]
How do you see the path being affected by `JsonReader.skipName()` and `JsonReader.promoteNameToValue()`?
I'm not sure how it should behave, wether we should ignore the value or simulate it and push it to the path stack.

**Comment by SimonMarquis** [comment]
I can see two behaviors at the moment:

- `JsonValueReader`:
  ```kotlin 
  @Test
  public void promoteNameToValue() throws Exception {
    JsonReader reader = factory.newReader("{\"a\":1}");
    reader.beginObject();
    reader.promoteNameToValue();
    assertThat(reader.getPath()).isEqualTo("$.a");
    assertThat(reader.peek()).isEqualTo(JsonReader.Token.STRING);
    assertThat(reader.nextString()).isEqualTo("a");
    assertThat(reader.getPath()).isEqualTo("$.a"); /* 👀 */
    /* ... */
  }
  ```

- `JsonUtf8Reader`:
  ```kotlin 
  @Test
  public void promoteNameToValue2() throws Exception {
    JsonReader reader = factory.newReader("{\"a\":1}");
    reader.beginObject();
    reader.promoteNameToValue();
    assertThat(reader.getPath()).isEqualTo("$.a");
    assertThat(reader.peek()).isEqualTo(JsonReader.Token.STRING);
    assertThat(reader.nextString()).isEqualTo("a");
    assertThat(reader.getPath()).isEqualTo("$."); /* 👀 */
    /* ... */
  }
  ```

**Comment by swankjesse** [comment]
@SimonMarquis ooooh good question, and I see how this is problematic. I think this behavior is nicer:

```
  assertThat(reader.getPath()).isEqualTo("$.a"); /* 👀 */
```

I prefer that because if there’s a problem **within** the value for `a` we want the path to indicate that. I’m not sure if that’s super tricky to achieve!

**Comment by SimonMarquis** [comment]
There is one remaining class of issues I'm facing with [this test](https://github.com/square/moshi/blob/3cbd5c327a0e2c1d150fdaa2c04202dfa82450e8/kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt#L148-L158):

`KotlinJsonAdapter` correctly decodes a `null` value, but throws because it it must not be nullable. But here it's too late, the path already changed.

https://github.com/square/moshi/blob/3cbd5c327a0e2c1d150fdaa2c04202dfa82450e8/kotlin/reflect/src/main/java/com/squareup/moshi/kotlin/reflect/KotlinJsonAdapter.kt#L86-L94

We could fix that by first checking if the reader is peeking a NULL token, but it wouldn't solve other variants of this bug like in [this test](https://github.com/square/moshi/blob/3cbd5c327a0e2c1d150fdaa2c04202dfa82450e8/kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt#L160-L179).
The token might not be NULL but the delegate could return a null value.

**Comment by SimonMarquis** [comment]
> We could fix that by first checking if the reader is peeking a NULL token

Well actually I found out it's an already expected behavior to first let the delegate parse the value (see [delegatesToInstalledAdaptersBeforeNullChecking](https://github.com/square/moshi/blob/3cbd5c327a0e2c1d150fdaa2c04202dfa82450e8/kotlin/tests/src/test/kotlin/com/squareup/moshi/kotlin/DualKotlinTest.kt#L190))

**Comment by swankjesse** [comment]
@SimonMarquis in that specific case I don’t think the failure is ambiguous, that unexpected null exception tells you the JSON name that was null and the path to the object that enclosed it.

**Comment by SimonMarquis** [comment]
I've updated the `JsonUtf8Reader` to correctly report the last `peekedString` to fix `promoteValueToName` tests.
But to be honest, I'm not confident at all with the solution I came up with.
I'd like to get your feedback on this. 🙏

**Comment by cleidiano** [comment]
Hi everyone, this PR have been stalling for a while, any plan to merge it?

**Pull request closed without merging**
