### PR TITLE
Add some beautiful graphics to the README

### PR DESCRIPTION
**Pull request by swankjesse**

### CODE REVIEW

**Comment by swankjesse** [comment]
Rendered: https://github.com/square/moshi/blob/6807cac23f02d082c81620011c19fab186da72dd/README.md

**Comment by JakeWharton** [comment]
I would check that this keeps the description above the fold for mobile users

**Comment by digitalbuddha** [comment]
Not quite above the fold on a pixel 3 in chrome. https://drive.google.com/file/d/1s-7sqGoCiqDiN5pGRzmLcFG4mBpA_xhB/view?usp=drivesdk couldnt figure out how else to share

**Comment by ZacSweers** [comment]
| | |
|-|-|
| image | image |

| | |

**Comment by JakeWharton** [comment]
I meant before the "read more" link when you're viewing the page. Mike's seems to indicate it as such.

**Comment by swankjesse** [comment]
I'm gonna hold off until we build a proper site for this.

**Pull request closed without merging**
