### PR TITLE
Add missing val and fix indentation in README

### PR DESCRIPTION
**Pull request by LouisCAD**

### CODE REVIEW

**Comment by swankjesse** [comment]
Thanks!

**Comment by JakeWharton** [comment]
Indentation was correct before.

**Comment by Egorand** [comment]
It's either 2 spaces or 4 spaces, but not 8

**Comment by LouisCAD** [comment]
Well, this PR has the Android Kotlin style guide which is 8 spaces in this case. It's right that Kotlin style guide by JetBrains is 4 spaces here, but the indentation was 2 spaces, which I don't recall seeing in either Kotlin style guide.

Feel free to edit it anyway.

**Comment by JakeWharton** [comment]
Both Android and Kotlin is 4. Square is 2, because we don't like wasting
horizontal space.

**Comment by LouisCAD** [comment]
@JakeWharton Continuation indent is 8 spaces in Android style guide: https://android.github.io/kotlin-guides/style.html#continuation-indent

**Comment by LouisCAD** [comment]
There has been no new commit since last year on the mast branch of the android Kotlin style guide: https://github.com/android/kotlin-guides/commits/master
I don't know what you're talking about...

**Comment by JakeWharton** [comment]
https://github.com/android/kotlin-guides/commit/41f576ea4a3155608ba7c1dde84251abcd012fe5

**Comment by LouisCAD** [comment]
If this change is so old, why it still didn't make it to the `gh-pages` branch?

**Comment by JakeWharton** [comment]
Haven't had time to push a new release

**Pull request merged**
