### PR TITLE
Hook up osstrich, a tool to publish Javadoc to GitHub pages.

### PR DESCRIPTION
**Pull request by swankjesse**

### CODE REVIEW

**Comment by swankjesse** [comment]
I didn't wire up `deploy_snapshot`, mostly ’cause that means we won't publish Javadoc for new releases until some unrelated change after the fact. Also (though minor) it means we’ll `git clone` the `gh-pages` repo more than strictly necessary.

...though I don't feel strongly here!

**Comment by swankjesse** [comment]
(once we figure out the right strategy here, I'll repeat for similar repos)

**Comment by JakeWharton** [comment]
Isn't it true that we already have to wait to publish since it uses the search API which is lagged up to 4 hours? Maybe a service isn't such a bad idea after all.

**Comment by JakeWharton** [comment]
LGTM though

**Comment by inder123** [comment]
Neat! We should set this up for Gson too.

**Pull request closed without merging**
