### PR TITLE
Workaround for android reflection bugs

### PR DESCRIPTION
**Pull request by kotucz**
There are android issues with reflection types, that cause Moshi to not find adapters for parametrized types.
Full description is in #148. Here I provide runnable android tests that show the issue and fix for the current issue.
The android test project is set up via gradle for now (sorry I can't maven :))

### CODE REVIEW

**Comment by swankjesse** [comment]
Please don't change our build system in your pull request.

**Comment by kotucz** [comment]
Sorry, I need to have the issue fixed. How can I run the android tests on the build system? The issue may not occur otherwise...

**Comment by JakeWharton** [comment]
We don't want Android-specific tests as part of the project. You should be able to implement your own `ParameterizedType` which violates the `equals` contract in the same way to trigger the erroneous behavior on the JVM.

**Comment by kotucz** [comment]
Created new pull request #155

**Pull request closed without merging**
