### PR TITLE
Notify about class constructor errors (missing/multiple primary?)

### PR DESCRIPTION
**Pull request by IlyaGulya**
Hello!

Now code generator simply crashes when it does not find any primary constructor in kotlin class.
This PR provides clarification to the user of library about what exactly has happened.

### CODE REVIEW

**Comment by ZacSweers** [comment]
Hey - sorry for the delay on this, I was traveling this summer. Can you add a test for these? There's some basic apt errors tests in `kotlin/codegen/src/test`

**Comment by IlyaGulya** [comment]
> Hey - sorry for the delay on this, I was traveling this summer. Can you add a test for these? There's some basic apt errors tests in `kotlin/codegen/src/test`

Sure, will make them soon.

**Comment by ZacSweers** [comment]
Actually, are either of these cases possible after all the other checks we have?

**Comment by ZacSweers** [comment]
Closing this for now

**Pull request closed without merging**
