### PR TITLE
Include the cause when an adapter method fails.

### PR DESCRIPTION
**Pull request by swankjesse**

### CODE REVIEW

**Comment by JakeWharton** [comment]
needs rebase

**Comment by swankjesse** [comment]
Uh oh, once I rebase I see this change has already been made. Nice.

**Comment by janswist** [comment]
Great! How can I access this upgrade? Should I upgrade dependency (I still see 1.2.0)?

**Comment by swankjesse** [comment]
I hope to cut a new release soon. In the interim please use our snapshots

**Pull request closed without merging**
